version: "3.5"
services:
  terraform:
    container_name: terraform
    build:
      context: .
      dockerfile: ./Dockerfile
      target: terraform
    # env_file:
    #   - .env
    working_dir: /iac
    volumes:
      - ./:/iac
    networks:
      - terraform
networks:
  terraform:
    driver: bridge